In [1]:
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import os
import pydicom
from ipywidgets import interact, IntSlider

from glob import glob
import torch


from ipywidgets import fixed


In [2]:
train_list = glob("/ssd2/colono/data/TrainDataset/image/*.png")
train_mask_list = glob("/ssd2/colono/data/TrainDataset/mask/*.png")


# 정렬
train_list.sort()
train_mask_list.sort()

In [3]:
print(len(train_list), len(train_mask_list))

1450 1450


In [4]:
# 이미지 read
# 이미지 사이즈 범위 출력. 전체 파일
sizes = []
for i in train_list:
    img = cv2.imread(i)
    sizes.append(img.shape)
sizes = np.array(sizes)
print(sizes.min(axis=0), sizes.max(axis=0),len(sizes))


[288 332   3] [1072 1920    3] 1450


In [5]:
# 이미지 확인
def show_image(idx):
    plt.figure(figsize=(10, 10))
    plt.subplot(1, 2, 1)
    image = plt.imread(train_list[idx])
    plt.imshow(image, cmap='gray')
    plt.subplot(1, 2, 2)
    mask = plt.imread(train_mask_list[idx])
    plt.imshow(mask, cmap='gray')

interact(show_image, idx=IntSlider(min=0, max=len(train_list)-1, step=1, value=0))


interactive(children=(IntSlider(value=0, description='idx', max=1449), Output()), _dom_classes=('widget-intera…

<function __main__.show_image(idx)>

In [6]:
# testset 확인

cvc_list = glob("/ssd2/colono/data/TestDataset/CVC-300/images/*.png")
cvc_clinic = glob("/ssd2/colono/data/TestDataset/CVC-ClinicDB/images/*.png")
cvc_colon = glob("/ssd2/colono/data/TestDataset/CVC-ColonDB/images/*.png")
etis_list = glob("/ssd2/colono/data/TestDataset/ETIS-LaribPolypDB/images/*.png")
Kvasir_list = glob("/ssd2/colono/data/TestDataset/Kvasir/images/*.png")

cvc_list.sort()
cvc_clinic.sort()
cvc_colon.sort()
etis_list.sort()
Kvasir_list.sort()

In [7]:
# testset 확인

cvc_list_mask = glob("/ssd2/colono/data/TestDataset/CVC-300/masks/*.png")
cvc_clinic_mask = glob("/ssd2/colono/data/TestDataset/CVC-ClinicDB/masks/*.png")
cvc_colon_mask = glob("/ssd2/colono/data/TestDataset/CVC-ColonDB/masks/*.png")
etis_list_mask = glob("/ssd2/colono/data/TestDataset/ETIS-LaribPolypDB/masks/*.png")
Kvasir_list_mask = glob("/ssd2/colono/data/TestDataset/Kvasir/masks/*.png")

cvc_list_mask.sort()
cvc_clinic_mask.sort()
cvc_colon_mask.sort()
etis_list_mask.sort()
Kvasir_list_mask.sort()

In [8]:
# testset 리스트들의 사이즈 범위와 갯수 확인


for dataset in [cvc_list, cvc_clinic, cvc_colon, etis_list, Kvasir_list]:
    
    sizes = []
    if dataset == cvc_list:
        print("CVC-300")
    elif dataset == cvc_clinic:
        print("CVC-ClinicDB")
    elif dataset == cvc_colon:
        print("CVC-ColonDB")
    elif dataset == etis_list:
        print("ETIS-LaribPolypDB")
    elif dataset == Kvasir_list:
        print("Kvasir")

    for i in dataset:
        img = cv2.imread(i)
        sizes.append(img.shape)

    sizes = np.array(sizes)
    print(sizes.min(axis=0), sizes.max(axis=0),len(sizes))




CVC-300
[500 574   3] [500 574   3] 60
CVC-ClinicDB
[288 384   3] [288 384   3] 62
CVC-ColonDB
[500 574   3] [500 574   3] 380
ETIS-LaribPolypDB
[ 966 1225    3] [ 966 1225    3] 196
Kvasir
[352 490   3] [1070 1348    3] 100


In [9]:
def show_image_test(idx,test_list,test_mask_list):
    plt.figure(figsize=(10, 10))
    plt.subplot(1, 2, 1)
    image = plt.imread(test_list[idx])
    plt.imshow(image, cmap='gray')
    plt.subplot(1, 2, 2)
    mask = plt.imread(test_mask_list[idx])
    plt.imshow(mask, cmap='gray')

In [10]:

interact(show_image_test, idx=IntSlider(min=0, max=len(cvc_list)-1, step=1, value=0), test_list=fixed(cvc_list), test_mask_list=fixed(cvc_list_mask))


interactive(children=(IntSlider(value=0, description='idx', max=59), Output()), _dom_classes=('widget-interact…

<function __main__.show_image_test(idx, test_list, test_mask_list)>

In [11]:


interact(show_image_test, idx=IntSlider(min=0, max=len(cvc_clinic)-1, step=1, value=0), test_list=fixed(cvc_clinic), test_mask_list=fixed(cvc_clinic_mask))


interactive(children=(IntSlider(value=0, description='idx', max=61), Output()), _dom_classes=('widget-interact…

<function __main__.show_image_test(idx, test_list, test_mask_list)>

In [12]:



interact(show_image_test, idx=IntSlider(min=0, max=len(cvc_colon)-1, step=1, value=0), test_list=fixed(cvc_colon), test_mask_list=fixed(cvc_colon_mask))



interactive(children=(IntSlider(value=0, description='idx', max=379), Output()), _dom_classes=('widget-interac…

<function __main__.show_image_test(idx, test_list, test_mask_list)>

In [13]:



interact(show_image_test, idx=IntSlider(min=0, max=len(etis_list)-1, step=1, value=0), test_list=fixed(etis_list), test_mask_list=fixed(etis_list_mask))


interactive(children=(IntSlider(value=0, description='idx', max=195), Output()), _dom_classes=('widget-interac…

<function __main__.show_image_test(idx, test_list, test_mask_list)>

In [14]:




interact(show_image_test, idx=IntSlider(min=0, max=len(Kvasir_list)-1, step=1, value=0), test_list=fixed(Kvasir_list), test_mask_list=fixed(Kvasir_list_mask))


interactive(children=(IntSlider(value=0, description='idx', max=99), Output()), _dom_classes=('widget-interact…

<function __main__.show_image_test(idx, test_list, test_mask_list)>